### ISSUE TITLE
[enhancement] use of virtualenv for python and ruby for all non packaged tools

### ISSUE THREAD

**Issue by cyrinux** [koutto/jok3r#21]
Hey @koutto,
I see you allready use rvm for whatweb, we should use python/ruby virtualenv for each non packaged tools.
I broke my metasploit due to a nokigiri conflict for example.
In the tools install worflow I think we should try to detect the language and force a virtualenv creation.
Or simply do this manually in the install/update/exec config part of each tools.
What do you think about this?
About ruby maybe think to use rvm gemset to be lighter.

**Comment by koutto** [comment]
Yes, I used rvm for whatweb because whatweb is not working well on latest Ruby version for obscure reasons (I saw several issues related to this problem). And I am not an expert in Ruby =)
Using virtualenvs is a good idea to improve the global stability. I just hope it won't increase the total size too much. I will take this point and experiment first with Python virtualenv.

**Comment by cyrinux** [comment]
A little update about this, i read that by default on linux virtualenv use link so I think this will not grow much. To be tested.
