### ISSUE TITLE
[bug] missing colmn name  name_original

### ISSUE THREAD

**Issue by cyrinux** [koutto/jok3r#28]
![image](https://user-images.githubusercontent.com/519083/61884357-61f5c880-aefc-11e9-97c4-3fa01664fc2e.png)

**Comment by koutto** [comment]
It is due to the fact I had to update the database architecture and add a new column (name_original) inside the "Service" table.
Therefore, it is required to start from a fresh local.db file if you want to use the latest sources... Just delete the "local.db" file and re-run Jok3r (it will re-create a database with all the tables and columns). Unfortunately, you lose all the data you had stored before.

If you want to keep the data, maybe you can manually add the new column with something like:
`sqlite local.db`
`alter table services add column name_original char(100)`

**Comment by koutto** [comment]
That's also why I am not updating the Docker image at the moment, because there are some modifications on the core going on, I will do it asap when it will become more stable !
Also working on a better way to perform update

**Comment by cyrinux** [comment]
Thanks, i'm dumb sorry, i read the commit but don't realize you don't manage migartion yet. Do you plan to use something like https://pypi.org/project/alembic/ ?
I'm just working with for improve the tools with you for the moment, so don't worry :)

**Comment by koutto** [comment]
Yes, and also perform a re-install of tools for which there has been a modification in install/update command in the toolbox.conf file.
Also, automating checks of correct install for each tool, based on exit code, as much as possible.
Goal would be to use Travis CI to perform automated check, and to automate deploy of updated image on Docker Hub if no error has been detected

**Comment by cyrinux** [comment]
I'm totally ok with this future  workflow. We should also add some linting/code  checker, eg black formatter.
