### ISSUE TITLE
"Database is Locked"

### ISSUE THREAD

**Issue by bowojori7** [koutto/jok3r#40]
I get an error message when I try to start a scan: "Database is locked"

I have been running multiple scans with zero issues for a while now. 

One of the scans encountered the same error and I quit it. Subsequent scans have been stopping with the same error at the "check if service is reachable" point at the beginning of the scan

.

Help please.

I have attached screenshots for clarity.

![Screen Shot 2019-12-19 at 12 32 34](https://user-images.githubusercontent.com/26433851/71170494-b313a980-225b-11ea-9416-b4a1bb25f96b.png)
![Screen Shot 2019-12-19 at 12 32 42](https://user-images.githubusercontent.com/26433851/71170497-b3ac4000-225b-11ea-8c57-61a98f88d864.png)

**Comment by koutto** [comment]
This issue is due to the limitation of sqlite that does not allow concurrent write access to the database.
If you continue to have this issue, run one jok3r process at a time, and if not enough, make a backup of your local.db file by moving it somewhere else. It will allow jok3r to start from a fresh database, but you lose the current content of course.
It is just a temporary solution, because i am moving to postgresql, which will remove this problem.

**Comment by bowojori7** [comment]
Thank you!
