### ISSUE TITLE
How to delete target from db?

### ISSUE THREAD

**Issue by mastercho** [koutto/jok3r#7]
I want to delete target from DB, how to do that?

And hope tools for SQLi,LFI,RFI,RCE added soon like SqlMap

**Comment by koutto** [comment]
Hi,
Best way to user Jok3r is with 2 shells opened in the Docker container:
- 1 used to launch attacks using `python3 jok3r attack [...]`
- 1 used to access the database in real-time, add new targets, see results, see detected products, vulns, creds, generate reports, etc.

To delete a target from the DB, use `services --ip <targetip> --del` after selecting the proper mission.
You can also apply other filters (instead of --ip), just refer to the command help:

> 
> jok3rdb[default]> services -h
> usage: services [-h]
>                 [-a <host> <port> <service> | -u <url> | -d | -c <comment> | --https]
>                 [--addcred <user> <pass> | --addcred-http <user> <pass> <auth-type> | --adduser <user> | --adduser-http <user> <auth-type>]
>                 [-H <hostname1,hostname2...>] [-I <ip1,ip2...>]
>                 [-p <port1,port2...>] [-r <protocol>] [-U] [-o <column>]
>                 [-S <string>]
>                 [<name1> <name2> ... [<name1> <name2> ... ...]]
> 
> Services in the current mission scope
> 
> optional arguments:
>   -h, --help                                show this help message and exit
> 
> Manage services:
>   -a, --add <host> <port> <service>         Add a new service
>   -u, --url <url>                           Add a new URL
>   -d, --del                                 Delete selected service(s) (instead of displaying)
>   -c, --comment <comment>                   Change the comment of selected service(s)
>   --https                                   Switch between HTTPS and HTTP protocol for URL of selected service(s)
> 
> Manage services credentials:
>   --addcred <user> <pass>                   Add new credentials (username+password) for selected service(s)
>   --addcred-http <user> <pass> <auth-type>  Add new credentials (username+password) for the specified authentication type on selected HTTP service(s)
>   --adduser <user>                          Add new username (password unknown) for selected service(s)
>   --adduser-http <user> <auth-type>         Add new username (password unknown) for the specified authentication type on selected HTTP service(s)
> 
> Filter services:
>   -H, --hostname <hostname1,hostname2...>   Search for a list of hostnames (comma-separated)
>   -I, --ip <ip1,ip2...>                     Search for a list of IPs (single IP/CIDR range comma-separated)
>   -p, --port <port1,port2...>               Search for a list of ports (single/range comma-separated)
>   -r, --proto <protocol>                    Only show [tcp|udp] services
>   -U, --up                                  Only show services which are up
>   -o, --order <column>                      Order rows by specified column
>   -S, --search <string>                     Search string to filter by
>   <name1> <name2> ...                       Services to select


I am wondering about adding tools like wapiti scanner, but I am scared that it will increase global time of scan too much. Maybe I should add another category of checks (like "extensive scan") that are not run by default, but could be selected by users. Will check that.
Don't hesitate if you have other suggestions.

Cheers

**Comment by mastercho** [comment]
Thank you for a quick answer, for me time doesn't matter. Results are matter hehe. I would like to see scan to websites which are in the same server.  I will investigate jok3er code a bit. Its large project and i like it :)

**Comment by koutto** [comment]
Cool man, I will check that. Don't hesitate to contribute or give other ideas.
